### ISSUE TITLE
No xxx_21cf file exists

### ISSUE THREAD

**Issue by crazyegg111** [HearingTechnology/CoNNear_periphery#1]
i want to reprwoduce the ICASSP2022 article, so I need this file. I don't know how to modify it. By the way, I would like to ask if the implementation code of this article will be open source

**Comment by fotisdr** [comment]
Hi,

First of all, 21 CFs can be simulated with the existing repository by using the 1cf files instead. A simple way to do this is by modifying the `connear_example.py` file to keep 21 frequency channels out of the 201, by adding a line after line 113 that indexes the 3rd (frequency) dimension of the vbm variable from 0 to 200 with a step of 10 (make sure that the fullcf_simulation = 0 in the script). Otherwise, the build_connear function in the `connear_functions.py` file can be modified instead to have a CF selection integrated in the model definition, e.g. by adding the following lines between lines 103 and 104:
```
Ncf = 21 # number of CFs to keep
# Select cochlear CFs
cochlea_cfs = K.arange(0,201,int((201-1)/(Ncf-1)))
cochlea_out = Lambda(lambda x: tf.gather(x,cochlea_cfs,axis=2), name='freq_downsampling')(cochlea_out)
```

If you would still prefer to do this with the 21cf json files (and possibly have a parallel simulation of all channels with fullcf_simulation = 1), please provide me your e-mail and I can send these files to you. In case there is more interest for these pre-compiled 21-CF json files I can also add them to the repository.

Unfortunately the code of the ICASSP article has not been published online yet, but we plan on making the whole closed-loop framework publicly available as soon as possible.

Fotis

**Comment by crazyegg111** [comment]
Thank you very much for your kind help, it would be great if I could get those documents, my email address is duhui9906@163.com, and finally, thank you for your contribution to this field
